c_stdlib_version:          # [osx and x86]
  - '10.14'                # [osx and x86]

c_compiler:    # [win]
  - vs2019     # [win]
cxx_compiler:  # [win]
  - vs2019     # [win]

c_stdlib_version:   # [linux]
  - "2.17"          # [linux]
