{% set name = "robotpy-cscore" %}
{% set version = "2023.1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d08dc7166e4b7d2c2690eae0ecfdc570ddb4f16c008f82c8030565fe8bcd6700
  patches:
    - no-cxx20.patch  # [not win]

build:
  number: 0
  skip: true  # [py<35]

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # V4L2_CTRL_TYPE_INTEGER_MENU was added in Linux 3.5
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - numpy
    - pip
    - pkgconfig
    - py-opencv
    - pybind11
    - python
  run:
    - pynetworktables
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('libopencv', max_pin='x.x') }}
    - {{ pin_compatible('py-opencv', max_pin='x.x') }}

test:
  imports:
    - _cscore
    - cscore
    - cscore.grip
    - cscore.imagewriter
  commands:
    - pip check
    - python -m cscore --help
  requires:
    - pip

about:
  home: https://github.com/robotpy/robotpy-cscore
  summary: Python bindings for the CSCore image processing library used in FRC
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://robotpy.readthedocs.io/projects/cscore/en/stable/api.html

extra:
  recipe-maintainers:
    - auscompgeek
