{% set name = "robotpy-cscore" %}
{% set version = "2022.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d917ec8783721bdd7d819023da6755b0ec0f13085f2b6decacce6735caca7b80

build:
  number: 0
  skip: true  # [py<35]

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # V4L2_CTRL_TYPE_INTEGER_MENU was added in Linux 3.5
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - numpy
    - pip
    - pkgconfig
    - py-opencv
    - pybind11
    - python
  run:
    - pynetworktables
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('libopencv') }}
    - {{ pin_compatible('py-opencv') }}

test:
  imports:
    - _cscore
    - cscore
    - cscore.grip
    - cscore.imagewriter
  commands:
    - pip check
    - python -m cscore --help
  requires:
    - pip

about:
  home: https://github.com/robotpy/robotpy-cscore
  summary: Python bindings for the CSCore image processing library used in FRC
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://robotpy.readthedocs.io/projects/cscore/en/stable/api.html

extra:
  recipe-maintainers:
    - auscompgeek
